const SYSTEMS = {
  half_guard: {
    label: 'Half Guard',
    tree: {
      id: 'hg_root', label: 'Half Guard', type: 'root',
      info: { title: 'Half Guard – Core Concepts', body: `<b>Tavoite:</b> Estä vastustajaa litistämästä sinua mattoon ja luo kulmia tai etäisyyttä hyökkäyksille.<br><br><b>Tärkeimmät yksityiskohdat:</b><ul><li><b>Kylkiasento:</b> Pysy aina tiukasti kyljelläsi. Hartiat matossa = vaara.</li><li><b>Kehykset/Frames:</b> Pidä päällimmäinen käsi vastustajan rinnan tai hartian poikki vastustamaan painoa.</li><li><b>Alempi käsi:</b> Estä aktiivisesti crossface hauislihaksella tai ranteella.</li></ul>Tästä valitset suuntasi sen perusteella, mihin vastustaja antaa painoa tai jättää tilaa.` },
      children: [
        {
          id: 'knee_shield', label: 'Knee Shield', sub: 'Z-Guard / Distance', type: 'category',
          info: { title: 'Knee Shield / Z-Guard', body: `<b>Suunta:</b> Etäisyyden hallinta ja ohituksen pysäyttäminen.<br><br><b>Miten päästä positioon:</b><ol><li><b>Kilpi:</b> Aja päällimmäinen polvesi vastustajan rintaan tai hauikseen (Z-muoto).</li><li><b>Alempi hookki:</b> Kontrolloi lantiota tai sisäreittä alemmalla jalalla.</li><li><b>Kehykset/Frames:</b> Pidä kädet vahvoina pitääksesi paineen poissa ylävartalostasi.</li></ol><b>Huomio:</b> Erinomainen peruspositio isompia vastustajia vastaan ennen siirtymistä lähitaisteluun.` },
          children: [
            { id: 'ks_arm_drag', label: 'Arm Drag', info: { title: 'Arm Drag to Back', body: `<b>Tilanne:</b> Vastustaja nojaa kilpeesi tai kurottaa kaulukseen/kasvoihin.<br><br><b>Suoritus:</b><ul><li>Ota ristiote kurottavasta hihasta tai ranteesta saman puolen kädellä.</li><li>Vedä kättä terävästi rintasi yli samalla kun avaat kilpipolven.</li><li>Käytä liike-energiaa kiivetäksesi ylös ja suoraan selkään.</li></ul>` } },
            { id: 'ks_dogfight', label: 'Dogfight Entry', info: { title: 'Transition to Dogfight', body: `<b>Tilanne:</b> Vastustaja jäätyy kilpeä vasten tai istuu taaksepäin; haluat vaihtaa etäisyyden lähitaisteluun.<br><br><b>Suoritus:</b><ul><li>Pudota polvikilpi nopeasti reiden ohi.</li><li>Ammu ulompi käsi syvälle kainaloon (underhook) samalla liikkeellä.</li><li>Nouse: kyynärpää → käsi → polvi = Dogfight.</li></ul>` } },
            { id: 'ks_john_wayne', label: 'John Wayne Sweep', info: { title: 'John Wayne Sweep (Knee Lever)', body: `<b>Tilanne:</b> Vastustaja antaa raskasta painetta kilpeesi yrittäen romahduttaa sen.<br><br><b>Suoritus:</b><ul><li>Lukitse molemmat jalat tiukasti ohittavan jalan ympärille (nilkka nilkkaan).</li><li>Ota kiinni lähimmästä hihasta molemmin käsin (2-on-1).</li><li>Ammu lantiosi pitkin mattoa ja väännä vastustajan polvea terävästi sivulle — polvi toimii tukipisteenä, joka vie kaiken tasapainon.</li></ul>` } },
          ]
        },
        {
          id: 'kimura_trap', label: 'Kimura Trap', sub: 'Upper body control', type: 'category',
          info: { title: 'Kimura Trap System', body: `<b>Suunta:</b> Ylävartalon hyökkäys whizzereitä, matalia ohituksia tai matossa olevia käsiä vastaan.<br><br><b>Miten päästä positioon:</b><ol><li><b>Ote:</b> Saman puolen käsi tarttuu ranteeseen. Vie toinen käsi yli ja ali ja tartu omaan ranteeseesi (figure-4 / kimura lock).</li><li><b>Yhdistä:</b> Vedä lukko tiukasti rintaasi vasten — älä koskaan anna sen kellua irti kehyksestäsi.</li></ol><b>Huomio:</b> Yksi vahvimmista kontrolleista BJJ:ssä. Voidaan käyttää lopetuksena tai vipuvarrena sweepeissä.` },
          children: [
            { id: 'kt_sweep', label: 'Kimura Sweep', info: { title: 'Kimura Sweep', body: `<b>Tilanne:</b> Sinulla on Kimura, mutta vastustaja istuu raskaasti leveällä perusasennolla.<br><br><b>Suoritus:</b><ul><li>Lukitse jalat tiukasti alaselän yli tai aseta perhoskoukku (butterfly hook).</li><li>Aja kättä lukon avulla kohti kainaloa ja taaksepäin, luoden jäykän vipuvarren.</li><li>Käytä koko vartaloasi ja koukkujasi heittääksesi hänet sivuttain hartialleen.</li></ul>` } },
            { id: 'kt_roll', label: 'Roll to Back', info: { title: 'Roll to Back / Tarikoplata', body: `<b>Tilanne:</b> Vastustaja ajaa voimakkaasti eteenpäin estääkseen Kimura sweepin.<br><br><b>Suoritus:</b><ul><li>Ohjaa paine uudelleen liu'uttamalla pääsi vastustajan painon alle kohti mattoa.</li><li>Säilytä Kimura-lukko ja pyörähdä (roll) alemman hartian ja niskan yli.</li><li>Nouset suoraan selkäkontrolliin, tai avaat Tarikoplata-mahdollisuuden astumalla jalkasi käden yli.</li></ul>` } },
            { id: 'kt_finish', label: 'Submission', info: { title: 'Kimura Submission', body: `<b>Tilanne:</b> Vastustajan käsi ajelehtii liian kauas kehosta tai ojentuu ristiin.<br><br><b>Suoritus:</b><ul><li>Pyörähdä selällesi, heitä päällimmäinen jalka alaselän yli estääksesi pyörähtämisen (rollout).</li><li>Käytä kauimmaista perhoskoukkua asettaaksesi hänet oikeaan kulmaan.</li><li>Pieni kierto ja aja rannetta kohti yläselkää — taputus.</li></ul>` } },
          ]
        },
        {
          id: 'butterfly_half', label: 'Butterfly Half', sub: 'Elevation / Lift', type: 'category',
          info: { title: 'Butterfly Half Guard', body: `<b>Suunta:</b> Pysäytä eteenpäin suuntautuva paine ja tuhoa tasapaino elevaatiolla (nostolla).<br><br><b>Miten päästä positioon:</b><ol><li>Luo tilaa katkaravulla (shrimp) tai hyödynnä tilanne, kun vastustaja nojaa eteen.</li><li>Aseta vapaa jalkasi reisien väliin perhoskoukuksi (jalkapöytä sisäreidellä).</li><li>Pumppaa koukulla pitääksesi painopisteen epävakaana aina kun vastustaja puskee sisään.</li></ol>` },
          children: [
            { id: 'bh_sweep', label: 'Butterfly Sweep', info: { title: 'Butterfly Sweep', body: `<b>Tilanne:</b> Vastustaja ajaa ylitsesi raskaalla paineella yrittäen litistää sinut.<br><br><b>Suoritus:</b><ul><li>Tiukka overhook pään puolen kädellä; underhook tai pään kontrolli kauimmaisella kädellä.</li><li>Kaadu reilusti underhookin puolelle.</li><li>Potkaise ja nosta perhoskoukulla viistosti ylöspäin — kuin jalkaprässi kattoon.</li><li>Seuraa liikettä suoraan mounttiin säilyttäen otteet pyörähdyksen ajan.</li></ul>` } },
            { id: 'bh_slx', label: 'Single Leg X Entry', info: { title: 'Transition to Single Leg X (Ashi Garami)', body: `<b>Tilanne:</b> Vastustaja leventää asentoaan tai ajaa taaksepäin estäen sweepin.<br><br><b>Suoritus:</b><ul><li>Käytä koukkua vain osittaiseen nostoon (painon keventäminen, ei täysi nosto).</li><li>Pujota alempi koukku syvälle jalkojen väliin asettaen jalkapöytäsi kauimmaisen jalan ulkopuolelle.</li><li>Paina toinen jalkasi saman jalan takaosaan — vahva SLX-positio (Ashi Garami), joka avaa jalkalukot ja pystyynnousu-sweepit.</li></ul>` } },
          ]
        },
        {
          id: 'rdlr', label: 'RDLR', sub: 'Reverse De La Riva', type: 'category',
          info: { title: 'Reverse De La Riva (RDLR)', body: `<b>Suunta:</b> Half Guardin vastaus, kun vastustaja nousee seisomaan tehdäkseen Knee Slide -ohituksen.<br><br><b>Miten päästä positioon:</b><ol><li>Vastustaja ponnahtaa pystyyn luoden dynaamisen Knee Slice -uhan.</li><li>Litistä ylävartalosi. Kierrä sisempi (alempi) half guard -jalkasi seisovan jalan ulkopuolelta takareiteen.</li><li>Aseta vapaan jalkasi jalkapohja lantiolle — paineen ja etäisyyden hallinta.</li></ol>` },
          children: [
            { id: 'rdlr_kiss', label: 'Kiss of the Dragon', info: { title: 'Kiss of the Dragon', body: `<b>Tilanne:</b> Vastustaja ajaa eteenpäin luoden raskaan paineen RDLR-koukkuun.<br><br><b>Suoritus:</b><ul><li>Vapauta lantiota kontrolloiva jalka, anna vastustajan tulla hieman eteenpäin ja tartu kauimmaiseen nilkkaan alhaaltapäin.</li><li>Käytä RDLR-koukkua tukipisteenä invertataksesi (kääntyäksesi ylösalaisin) lantiosi kohti kattoa jalkojen väliin.</li><li>Kierrä kehosi jalan ympäri — nouset esiin suoraan vastustajan takaa selkäkontrolliin (Back Take).</li></ul>` } },
            { id: 'rdlr_tripod', label: 'Tripod Sweep', info: { title: 'Tripod Sweep', body: `<b>Tilanne:</b> Vastustaja on varovainen, paino taaksepäin pitkässä asennossa yrittäen vääntää koukkuasi auki.<br><br><b>Suoritus:</b><ul><li>Ota tiukka ristiote kauimmaisesta nilkasta.</li><li>RDLR-koukku tukee yhtä puolta; toinen jalkasi asettuu poikittain lähi-lantion/säären yli (post).</li><li>Potkaise terävästi alaspäin lantiosta samalla kun vedät nilkkaa ylöspäin — poistaa tripod-tukikohtien tasapainon ja kaataa vastustajan taaksepäin.</li></ul>` } },
          ]
        },
        {
          id: 'dogfight', label: 'Dogfight', sub: 'Underhook', type: 'category',
          info: { title: 'Dogfight (Underhook Route)', body: `<b>Suunta:</b> Kainalon ali. Toimii, kun vastustaja jättää lähimmän kätensä auki.<br><br><b>Miten päästä positioon:</b><ol><li><b>Underhook:</b> Ammu ulompi käsi syvälle kainaloon, tartu selkälihakseen (lat) tai vyöhön. Pidä pääsi tiukasti rinnassa/leuassa kiinni — suoja giljotiinilta.</li><li><b>Alemman käden kontrolli:</b> Pidä kiinni kaukaisesta kädestä tai polvesta estääksesi crossfacen.</li><li><b>Nouse:</b> Vedä alempi jalkasi lantion alle → nouse kyynärpäälle → kädelle → polville = Dogfight.</li></ol>` },
          children: [
            { id: 'df_knee_tap', label: 'Knee Tap Sweep', info: { title: 'Knee Tap Sweep', body: `<b>Tilanne:</b> Vastustaja puskee sinua kohti (antaa takaisinpainetta) Dogfightissa.<br><br><b>Suoritus:</b><ul><li>Päästä irti matosta alemmalla kädellä (purista underhookia kovempaa), kurota pitkälle kaukaisempaan polveen.</li><li>Blokkaa (tap) polvi paikalleen, jotta hän ei voi astua taaksepäin.</li><li>Aja eteenpäin underhookilla ja koko kehon painolla, pää leuan/rinnan alla.</li><li>Pidä underhook kaatumisen läpi — päädyt vahvaan päällispositioon, et vastustajan guardiin.</li></ul>` } },
            { id: 'df_roll_under', label: 'Roll Under', info: { title: 'Roll Under Sweep', body: `<b>Tilanne:</b> Vastustaja puristaa voimakkaan whizzerin/overhookin underhook-käteesi painaen hartiaasi kohti mattoa.<br><br><b>Suoritus:</b><ul><li>Älä taistele painetta vastaan — vaihda suuntaa. Sukella päällesi alaspäin vastustajan keskipisteen (rinnan) alle.</li><li>Tartu lähimpään jalkaan (reiteen tai nilkkaan) alemmalla kädelläsi. Aja underhook-käsi syvemmälle haaroihin.</li><li>Pyörähdä sivuttain oman hartiasi yli.</li><li>Pyörähdys käyttää vastustajan whizzer-painetta tekemään hänestä painottoman — ohjaa hänet selälleen ja nouse päälle.</li></ul>` } },
            { id: 'df_back_take', label: 'Back Take', info: { title: 'Back Take from Dogfight', body: `<b>Tilanne:</b> Vastustaja yrittää karata nojaamalla taaksepäin tai vetämällä kätensä irti underhookistasi.<br><br><b>Suoritus:</b><ul><li>Painot karkaa taaksepäin — vedä itsesi underhookilla (tai arm dragilla) tiukemmin selkään.</li><li>Kurota kaukaisella kädellä kauimmaiseen lantioon (vyö/shortsit) kahden pisteen kontrollia varten.</li><li>Liukene nopeasti taakse, laita ensimmäinen hookki lantioon.</li><li>Seatbelt ensin (yksi käsi hartian yli, toinen kainalon alta) ennen toisen hookin hakemista — estää pakenemisen.</li></ul>` } },
          ]
        },
        {
          id: 'octopus', label: 'Octopus / 2.0', sub: 'Outside / Overhook', type: 'category',
          info: { title: 'Octopus / Octopus 2.0 (Overhook Route)', body: `<b>Suunta:</b> Yli ja ulkopuolelle. Toimii, kun vastustaja yrittää crossfacea jättäen ulkoreunan avoimeksi.<br><br><b>Miten päästä positioon:</b><ol><li><b>Octopus Grip:</b> Liu'u painon alle. Kurota päänpuoleisella kädelläsi yli selän vastustajan kauimmaiseen kainaloon/kylkeen. Olet nyt viistottain hänen selkänsä takana.</li><li><b>Octopus 2.0 (Butterfly Hook):</b> Nosta lantiotasi hieman ja sujahda alempi jalka jalkojen väliin asettaen perhoskoukku (jalkapöytä) sisäreiteen.</li></ol><b>Huomio:</b> Tämä hookki + selkäote on tuhoisa yhdistelmä — hookki kantaa painon tehden vastustajasta kevyen ja helposti pyöritettävän.` },
          children: [
            { id: 'oct_back_take', label: 'Back Take', info: { title: 'Back Take from Octopus', body: `<b>Tilanne:</b> Vastustaja jäätyy tai nojaa eteenpäin, eikä reagoi Octopus-otteeseen riittävän nopeasti.<br><br><b>Suoritus:</b><ul><li>Octopus-ote on vienyt sinut jo osittain taakse — jatka liikettä ylöspäin.</li><li>Käytä perhoskoukkua nostamaan lantiota hieman, tehden tilaa alemmalle polvellesi liukua alle ja selkään.</li><li>Heitä ulompi jalkasi lantion yli (twister hook) tai kiipeä suoraan seatbelt-selkäkontrolliin.</li></ul>` } },
            { id: 'oct_hip_bump', label: 'Hip Bump Sweep', info: { title: 'Hip Bump Sweep (Octopus)', body: `<b>Tilanne:</b> Vastustaja panikoi Octopus-uhan edessä, perääntyy nopeasti rintamasuunta eteenpäin ja nostaa ylävartaloaan.<br><br><b>Suoritus:</b><ul><li>Kun vastustaja nostaa painoaan ylös ja taakse, perusasento nousee irti matosta.</li><li>Säilytä tiukka ote vyötärön ympärillä. Nouse istumaan terävästi hänen kanssaan.</li><li>Aja lantiosi kovaa hänen kylkeensä (hip bump).</li><li>Olet hänen takanaan käsi ansassa — hän ei voi laittaa kättä mattoon postiksi. Seuraa suoraan mounttiin.</li></ul>` } },
            { id: 'oct_hook_sweep', label: 'Hook Sweep', sub: '(needs 2.0 hook)', info: { title: 'Hook Sweep (Octopus 2.0)', body: `<b>Tilanne:</b> Vastustaja ajaa rintaansa raskaasti alaspäin palauttaakseen normaalin half guard -paineen.<br><br><b>Suoritus:</b><ul><li>Älä työnnä vastaan — käytä sen sijaan perhoskoukkua.</li><li>Kaadu taaksepäin matalalle hartiallesi, vedä häntä tiukemmin Octopus-otteella.</li><li>Nosta samanaikaisesti perhoskoukulla — elevaten lantiota ylös ja sivulle.</li><li>Ohjaa ylävartalo (Octopus-ote) pään yli selkään. Seuraa päälle.</li></ul>` } },
            { id: 'oct_no_hook', label: 'Kosoto Hook', sub: '(outer leg, no butterfly)', info: { title: 'Kosoto Hook (Classic Octopus – No Butterfly Hook)', body: `<b>Konteksti:</b> Sinulla on Octopus-selkäote, mutta et ole saanut (tai et voi saada) perhoskoukkua sisään. Sen sijaan vapaa päällimmäinen jalkasi koukkaa <i>ulkopuolelta</i> kaukaisemman jalan polvitaipeen taakse — Ko-soto-tyylinen koukku, joka saavuttaa saman vipuvarren ulkoa.<br><br><b>Miten asettaa Kosoto-koukku:</b><ol><li>Heilauta Octopus-otteesta vapaa jalkasi yli ja koukkaa jalkaterä/kantapää takareiden taakse ulkopuolelta.</li><li>Tämä ansoittaa jalan koukkusi ja vastustajan oman kehon väliin — hän ei voi astua jalkaa pois.</li><li>Säilytä Octopus-selkäote tiukkana. Kontrolloit nyt ylävartaloa (otteella) ja kaukaisempaa jalkaa (koukulla).</li></ol><b>Mitä tehdä tästä:</b><ul><li><b>Ko-soto reap (Sweeppi):</b> Aja eteenpäin Octopus-otteella vetäen hänet ansassa olevan jalan yli. Koukku niittää polvea taaksepäin samalla kun kehosi paino tulee eteenpäin — vastustaja kaatuu sivulle/taakse ja seuraat suoraan päälle.</li><li><b>Selkäänmeno/Back take:</b> Käytä koukkua nostamaan ja keventämään kaukaisempaa jalkaa hieman. Pujota alempi polvesi taakse ja kiipeä selkään. Kosoto-koukku tekee tilaa, jonka perhoskoukku muuten loisi.</li><li><b>Pystyynnousu outside single legiin:</b> Nouse polvillesi pitäen Octopus-otteen, muuta polvikoukku perinteiseksi outside single-legiksi (nilkkapoiminta tai täysi viimeistely).</li></ul><b>Pääero perhoskoukkuun verrattuna:</b> Butterfly nostaa sisältä → hyvä elevaatiosweepeissä. Kosoto blokkaa/niittää ulkoa → parempi eteenpäin/sivulle ajamisessa ja alasvientityyppisissä lopetuksissa.` } },
          ]
        },
        {
          id: 'far_leg', label: 'Far Leg Attack', sub: 'Deep Half / Go Under', type: 'category',
          info: { title: 'Far Leg Attack (Deep Half Guard)', body: `<b>Suunta:</b> Kokonaan alle (Deep Half). Toimii raskasta litistämistä tai seisovia ohituksia vastaan.<br><br><b>Miten päästä positioon:</b><ol><li>Käytä kehyksiä houkutellaksesi eteenpäin suuntautuvaa painetta. Liu'u suoraan painopisteen alle — 'Homer Simpson' -tyylillä (litteänä mattoa pitkin).</li><li>Käännä kehosi kohtisuoraan. Piilota pää kauimmaisen takareiden/pohkeen taakse — suojassa giljotiineilta.</li><li>Tartu kauimmaiseen jalkaan (polvi tai reisi) molemmin käsin. Ansoita lähijalka jaloillasi. Nyt voit manipuloida tasapainoa kokonaan hänen altaan.</li></ol>` },
          children: [
            { id: 'fl_waiter', label: 'Waiter Sweep', info: { title: 'Waiter Sweep', body: `<b>Tilanne:</b> Vastustajan paino on suoraan yläpuolella tai hieman takana tasapainon säilyttämiseksi.<br><br><b>Suoritus:</b><ul><li>Tartu kauimmaisen polven taakse (Waiter Grip).</li><li>Asemoi jalkasi puristamaan kauimmaista reittä (pendulum / X-guard tyyliin).</li><li>Nosta kauimmainen jalka ja lantiosi suoraan ylöspäin kohti kattoa — kuin tarjoilija (waiter) pitäisi suurta tarjotinta yhdellä kädellä.</li><li>Kun tasapaino häiriintyy, keinu lantiolla ja vedä alempaa jalkaa kallistaen hänet sivulle tai taakse. Nouse päälle.</li></ul>` } },
            { id: 'fl_old_school', label: 'Old School / Homer', info: { title: 'Old School / Homer Simpson', body: `<b>Tilanne:</b> Vastustaja istuu hyvin raskaasti leveällä asennolla estäen nostavat sweepit.<br><br><b>Suoritus:</b><ul><li>Kurota kehon yli alemmalla kädellä — tartu jalkojesi välissä olevan lähijalan varpaisiin.</li><li>Vaihda lockdowniin ja vedä varpaita tiukasti takareisi-vedolla (back-heel pull) omaan pakaraasi.</li><li>Käänny vahvasti kasvot alaspäin, nouse polvillesi yhdellä sulavalla rullaavalla liikkeellä eteenpäin.</li><li>Varvasote tuhoaa kyvyn postata. Aja joko taaksepäin/sivulle ja nouse Side Controliin.</li></ul>` } },
            { id: 'fl_x_guard', label: 'X-Guard Entry', info: { title: 'X-Guard Transition', body: `<b>Tilanne:</b> Vastustaja vastustaa levittämällä kauimmaisen jalan leveälle tai nousemalla seisomaan vahvalla tasapainolla.<br><br><b>Suoritus:</b><ul><li>Ammu sisempi jalkasi (joka ansoitti halfissa) erittäin syvälle jalkojen väliin. Koukkaa kaukainen reisi/takaosa.</li><li>Aseta toinen jalkasi lähilantiolle — X-Guard -aloituspositio. Olet nyt painopisteen alla.</li><li>X-koukkujen avulla voit venyttää häntä pidemmälle ja suorittaa teknisen ylösnousu-sweepin, kipaten vastustajan taaksepäin.</li></ul>` } },
          ]
        },
      ]
    }
  },

  standing: {
    label: 'Standing Game',
    tree: {
      id: 'st_root', label: 'Standing', type: 'root',
      info: { title: 'Standing Game – Core Concepts', body: `<b>Tavoite:</b> Kontrolloi etäisyyttä ja horjuta vastustajaa saadaksesi alasviennin tai vetääksesi guardin hallitsevasta positiosta.<br><br><b>Kolme pääasetta:</b><ul><li><b>Arm Drag</b> — pääse selkään käden nopeudella (hand speed)</li><li><b>Standing Kimura Grip</b> — 2-on-1 kontrolli, joka riisuu hyökkäyksen ja avaa heittoja tai alasvientejä</li><li><b>Single Leg</b> — matalan riskin ja korkean tuoton alasvienti, joka ketjuuntuu kumpaankin edelliseen</li></ul>Alasviennin jälkeen: asetu Top Half Guardiin tai leikkaa suoraan läpi Knee Slidellä.` },
      children: [
        {
          id: 'arm_drag', label: 'Arm Drag', sub: 'Hand speed → back', type: 'category',
          info: { title: 'Arm Drag System', body: `<b>Tavoite:</b> Ohjaa käsi uudelleen nopeudella ja sujahda selän taakse ennen kuin hän ehtii reagoida.<br><br><b>Perus Arm Drag:</b><ol><li>Ota ristiote ranteesta saman puolen kädellä.</li><li>Samanaikaisesti koukkaa ojentajan/kyynärpään takaa toisella kädellä.</li><li>Nykiäistään käsivarsia terävästi kehon poikki — vedä, älä työnnä.</li><li>Astu samalla välittömästi taakse. Seatbelt → alasvienti selästä.</li></ol><b>Avain:</b> Astuminen ja vetäminen pitää tapahtua samanaikaisesti. Jos vedät ensin ja astut sitten, hän ehtii palautua.` },
          children: [
            { id: 'ad_back_take', label: 'Back Take → Takedown', info: { title: 'Arm Drag → Back Take → Takedown', body: `<b>Suoritus:</b><ul><li>Dragin jälkeen, astu tiukasti taakse ja ota heti seatbelt (päällimmäinen käsi hartian yli, alempi kainalon ali).</li><li>Aja eteenpäin tai kampita lähi-nilkka (osoto / ulkopuolen kampitus) viedäksesi hänet mattoon.</li><li>Seuraa suoraan selkäkontrolliin — aseta hookit tai siirry rear mountiin.</li></ul>` } },
            { id: 'ad_circle_post', label: 'Circle & Post Bait', info: { title: 'Circle & Post on Shoulder (Reaction Bait)', body: `<b>Konsepti:</b> Liiku sivuttain ja laita (post) kätesi kauimmaisen hartian taakse. Tämä pakottaa puolustuksellisen reaktion — heti kun vastustaja yrittää poistaa kätesi tai kääntyä sinuun päin, käsi on alttiina ohitukselle.<br><br><b>Suoritus:</b><ul><li>Astu sivulle, laita kämmen kauimmaisen hartian taakse.</li><li>Odota — kun hän siirtää kätensä poistaakseen omasi, ota välittömästi ristiote ranteesta ja tee arm drag.</li><li>Tämä luo ennakoitavan, korkean onnistumisprosentin entryn (kuzushi reaktiosta).</li></ul>` } },
          ]
        },
        {
          id: 'kimura_stand', label: 'Standing Kimura', sub: '2-on-1 figure-4', type: 'category',
          info: { title: 'Standing Kimura Grip', body: `<b>Tavoite:</b> 2-on-1 figure-four-ote, joka riisuu hyökkäävän käden ja antaa useita lopetuksia.<br><br><b>Ote:</b><ol><li>Ota ristiote ranteesta saman puolen kädellä.</li><li>Vie toinen kätesi käden yli ja ali, tarttuen omaan ranteeseesi (figure-4).</li><li>Kiinnitä lukko tiukasti omaan rintaasi — älä koskaan päästä sitä kellumaan vapaana.</li></ol><b>Avainperiaate:</b> Tällä otteella hän ei voi lyödä, ottaa kaulusotetta tai sukeltaa jalkoihin. Hallitset koko tilannetta.` },
          children: [
            { id: 'kst_takedown', label: 'Kimura Takedown', info: { title: 'Kimura Takedown (Shoulder Crank to Mat)', body: `<b>Suoritus:</b><ul><li>Kun ote on lukittu rintaasi, kierrä koko vartaloasi ja aja kyynärpää/hartia kohti mattoa.</li><li>Vastustaja tyypillisesti rullaa paineen alle tai menee kilpikonnaan (turtle).</li><li>Seuraa selkään tai Top Half Guardiin riippuen laskeutumisesta.</li></ul>` } },
            { id: 'kst_sumi', label: 'Sumi Gaeshi', info: { title: 'Sumi Gaeshi (Sacrifice Throw)', body: `<b>Tilanne:</b> Vastustaja vastustaa Kimura-alasvientiä nostamalla lantiota ja parantamalla ryhtiä.<br><br><b>Suoritus:</b><ul><li>Älä taistele ryhtiä vastaan — käytä sitä. Istu suoraan alas lantion alle pitäen Kimura-ote.</li><li>Aseta toinen tai molemmat perhoskoukut reisille.</li><li>Heitä hänet puhtaasti pään yli. Seuraa suoraan mounttiin.</li></ul>` } },
            { id: 'kst_single', label: 'Drop to Single Leg', info: { title: 'Standing Kimura → Single Leg', body: `<b>Tilanne:</b> Vastustajan ylävartalo on kiireinen taistellessaan otetta vastaan — etujalka on suojaamaton.<br><br><b>Suoritus:</b><ul><li>Nyki kättä alas ja eteenpäin Kimura-otteella rikkoaksesi ryhdin ja ladataksesi painon etujalalle.</li><li>Vaihda tasoa välittömästi ja ammu kohti painotettua jalkaa.</li><li>Olet jo käden sisäpuolella — giljotiinien riski on pieni. Viimeistele tavallisella single legillä.</li></ul>` } },
            { id: 'kst_armlock', label: 'Armlock', info: { title: 'Standing Armlock (Straight or Bent)', body: `<b>Tilanne:</b> Vastustaja vastustaa jäykällä suoralla kädellä tai kyynärpää on taipunut väännettävään asentoon.<br><br><b>Suoritus:</b><ul><li><b>Suora käsi:</b> Astu kyynärpään alle ja käytä ylöspäin suuntautuvaa vipua niveltä vastaan (ude gatame).</li><li><b>Taipunut käsi (Kimura):</b> Väännä figure-4 selän taakse — lopeta seisten tai vie hänet ensin mattoon.</li></ul>` } },
          ]
        },
        {
          id: 'single_leg', label: 'Single Leg', sub: 'Level change', type: 'category',
          info: { title: 'Single Leg Takedown', body: `<b>Tavoite:</b> Matalan riskin alasvienti, joka ketjuuntuu luonnollisesti Arm Dragiin ja Standing Kimuraan.<br><br><b>Entryt:</b><ol><li><b>Suora tasonvaihto:</b> Ponnahda polvista ja ammu suoraan etujalkaan — pää sisäpuolella suojaamassa giljotiineiltä.</li><li><b>Arm Drag hämäys:</b> Aloita arm drag; kun hän nykäisee kätensä takaisin (ladaten etujalan), ammu välittömästi single leg.</li><li><b>Kimura drop:</b> Vedä Kimura-otetta alas ladataksesi etujalan, ja ammu sitten.</li></ol>` },
          children: [
            { id: 'sl_run_pipe', label: 'Run the Pipe', info: { title: 'Run the Pipe (Single Leg Finish)', body: `<b>Tilanne:</b> Sinulla on single leg varmistettuna pää sisäpuolella, vastustaja hyppii.<br><br><b>Suoritus:</b><ul><li>Aja eteenpäin häntä kohti — 'running the pipe' — pakottaen peruuttamaan hallitsemattomasti.</li><li>Kun tukijalka luistaa tai hän yli-istuu taaksepäin, aja jalkaa kehosi poikki mattoon.</li><li>Viimeistele Top Half Guardiin tai leikkaa suoraan Knee Sliceen.</li></ul>` } },
            { id: 'sl_trip', label: 'Outside Trip', info: { title: 'Outside Trip / Ankle Pick', body: `<b>Tilanne:</b> Vastustaja sprawlaa tai astuu taaksepäin siirtäen lantion pois sinusta.<br><br><b>Suoritus:</b><ul><li>Kun hän astuu taaksepäin tukijalalla, kurota alas ulommalla kädelläsi ja poimi(pick) nilkasta.</li><li>Aja samalla eteenpäin kehon painolla — vastustaja kaatuu taaksepäin ilman tukipistettä.</li><li>Laskeudu Top Half Guardiin tai Side Controliin.</li></ul>` } },
          ]
        },
        {
          id: 'after_takedown', label: 'After Takedown', sub: 'Settle or cut', type: 'category',
          info: { title: 'Takedown Finish & Passing', body: `<b>Välitön päätös:</b> Sillä hetkellä kun vastustaja osuu mattoon, valitse yksi polku:<br><br><b>1. Rauhoita → Top Half Guard</b> — Vakauta, anna painetta ylhäältä, jauha kontrolloitu ohitus.<br><b>2. Leikkaa heti → Knee Slide</b> — Käytä alasviennin liike-energiaa ennen kuin hän ehtii asettaa kehyksiä (frames).` },
          children: [
            { id: 'td_half_guard', label: 'Top Half Guard', info: { title: 'Settle into Top Half Guard', body: `<b>Milloin:</b> Vastustaja laskeutui puolustavasti, sai kehyksen väliin, tai haluat kontrolloidumman ohituksen.<br><br><b>Suoritus:</b><ul><li>Pudottaudu Top Half Guardiin — kontrolloi lantiota polvellasi ja aseta crossface.</li><li>Tämä estää nopean scramble-pakenemisen ja antaa rakentaa murskaavaa yläpainetta.</li><li>Top Halfista: jauha Side Controliin, metsästä Kimura/Darce -ansoja, tai odota Knee Slice -avautumista.</li></ul>` } },
            { id: 'td_knee_slide', label: 'Knee Slide Pass', sub: 'Use the momentum', info: { title: 'Knee Slide / Knee Cut Pass', body: `<b>Milloin:</b> Vastustaja ei ole ehtinyt asettaa kehyksiä vielä — välittömästi alasviennin jälkeen ennen palautumista.<br><br><b>Kolme lopetusta:</b><ul><li><b>Standardi Knee Slide → Side Control:</b> Aja polvi kovaa läpi reiden ja lantion välistä. Crossface estää kääntymisen, liu'u läpi Side Controliin.</li><li><b>Knee Slide Mounttiin:</b> Jos lantio on litteänä ja jalat eivät blokkaa, liu'u ohitus kokonaan yli ja ota Mount suoraan — ohita Side Control.</li><li><b>Knee Slide → Back Take:</b> Kun vastustaja kääntyy sinua kohti epätoivossa, sukella suoraan taakse, koukkaa lähijalka (twister hook), ja ota seatbelt — varmista selkä.</li></ul>` } },
          ]
        },
      ]
    }
  }
};
